inherit_from: .rubocop_todo.yml
inherit_gem:
  rswag-specs: .rubocop_rspec_alias_config.yml
require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  DisabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - db/**/*
    - vendor/bundle/**/*
    - config/**/*
    - lib/tasks/**/*
    - bin/*

Performance:
  Exclude:
    - spec/**/*

Performance/BindCall:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/SelectMap:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

# Prefer assert_not over assert !
Rails/AssertNot:
  Include:
    - spec/**/*

# Prefer assert_not_x over refute_x
Rails/RefuteMethods:
  Include:
    - spec/**/*

Rails/IndexBy:
  Enabled: true

Rails/IndexWith:
  Enabled: true

# Prefer &&/|| over and/or.
Style/AndOr:
  Enabled: true
